---
- name: Create a test file
  hosts: all
  gather_facts: no
  become: yes

  tasks:
    - name: Create /tmp/hello.txt file
      ansible.builtin.file:
        path: /tmp/hello.txt
        state: touch
